import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

// The paper is generated by scripts/convert-paper.sh from docs/vphilox.tex.
const paper = defineCollection({
  loader: glob({ pattern: '**/*.mdx', base: './src/content/paper' }),
  schema: z.object({
    title: z.string(),
    author: z.string(),
  }),
});

// Hand-written explainers that carry the animated SVGs.
const docs = defineCollection({
  loader: glob({ pattern: '**/*.mdx', base: './src/content/docs' }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    order: z.number().default(99),
  }),
});

export const collections = { paper, docs };
